### ISSUE TITLE
Calcul du prix de livraison avec des incohérences de taxe et arrondi

### ISSUE THREAD

**Issue by karimou5** [frontBOI/mondial-relay#2]
# Problème : Calcul du prix de livraison avec des incohérences de taxe et arrondi

Je rencontre un problème avec le calcul du prix de livraison dans mon code, qui semble incohérent par rapport aux tarifs affichés par Mondial Relay.

## Description du problème

Lorsque j'essaie de calculer le prix de livraison avec le code suivant :

```javascript
const totalWeight = 1; // Calcul du poids total en grammes
const country = "FR"; // Pays de destination

const price = await getDeliveryPrice(totalWeight, country);
console.log('Delivery price:', price);
```

Le prix retourné pour un poids de 1g en destination FR est 4,188. Or, selon les tarifs affichés par Mondial Relay, le minimum pour une livraison devrait être 4,20 €. Vous pouvez consulter leurs tarifs ici : [Tarifs Mondial Relay.](https://www.mondialrelay.fr/envoi-de-colis/tarifs-expeditions/)

## Problèmes rencontrés

1. **Prix en TTC ?** Le prix semble inclure la taxe, mais cela n'est pas clair dans la documentation. Pouvez-vous confirmer si le retour de la fonction est bien en TTC ?
2. **Arrondi ?** Il y a un écart d'arrondi étrange, car le prix minimum devrait être de 4,20 €, mais je reçois 4,188. Cet arrondi semble bizarre et ne correspond pas aux attentes.

Je ne suis pas sûr si le problème vient de la fonction `getDeliveryPrice` ou si j'ai mal implémenté quelque chose dans mon code.

Merci d'avance pour votre aide !

**Comment by frontBOI** [comment]
Bonsoir @jins5 et merci pour votre ticket bien formaté. Par rapport à vos problèmes:

1. **Le prix est effectivement en TTC** avec 20% de TVA appliqués.
2. L'implémentation de la fonction `getDeliveryPrice` se base sur [la grille de tarif pour professionnel](https://www.mondialrelay.fr/solutionspro/offres-et-services/offre-start/tarifs-et-paiement/). Je n'ai à ce jour pas implémenté de fonction permettant de récupérer les prix pour une livraison entre particuliers, mais si besoin est je peux m'y atteler.

**Comment by karimou5** [comment]
Parfait, merci beaucoup @frontBOI pour la réponse rapide !

Si c'est déjà en prix professionnel, c'est parfait pour moi ! Pas besoin de développer la fonction pour la livraison entre particuliers alors, et encore merci aussi pour le paquet, il allège énormément notre travail !

Merci encore pour ta réactivité !
Je clos l'issue qui n'en est pas une ;)

Bonne soirée !
