### ISSUE TITLE
Questions sur l'API Mondial Relay et alternatives d'envoi de colis

### ISSUE THREAD

**Issue by karimou5** [frontBOI/mondial-relay#5]
Bonjour,

J'ai plusieurs questions en tête, et je me demandais si vous pouviez m'aider à y répondre :

1. Est-il possible de récupérer le numéro de suivi Mondial Relay avant de générer une étiquette via leur API ?
2. La génération d'étiquettes via l'API Mondial Relay est-elle payante si on utilise un compte avec les identifiants de production ?
3. Connaissez-vous un autre service ou une alternative pour l’envoi de colis ? (un package npm incroyable comme le vôtre, peut-être ?)

Merci beaucoup pour votre temps et vos réponses ! 😊

**Comment by frontBOI** [comment]
Bonjour @jins5, alors ce que je peux vous répondre:

1. **Non**: un numéro de suivi est obtenu après génération d'une étiquette, puisque qu'une étiquette est obtenue en créant un envoi chez Mondial Relay 🚛
2. **Oui**: en production, pour pouvoir créer un envoie (et donc obtenir une étiquette), il vous faut **créditer votre compte**  afin de permettre à Mondial Relay de débiter celui-ci pour qu'ils créent votre envoi. Sans crédit suffisant, la création d'un envoi échouera et mon package vous renverra une erreur (attention, les messages d'erreur de MR sont assez... énigmatiques lol).
3. Il existe pléthore de services de livraison (Colissimo, UPS...), pour lesquels je n'ai pas créé de package (encore ?). Je me suis concentré sur Mondial Relay car un client souhaitait le voir intégré à son site internet, et vu la galère que ça a été je me suis dit autant le partager !

**Comment by karimou5** [comment]
> 1. un numéro de suivi est obtenu après génération d'une étiquette

Merci beaucoup ! J’ai essayé, et effectivement, le numéro de suivi correspond bien au N° Expédition.

Par ailleurs, est-ce obligatoire de renseigner le contenu dans le champ ``createShipment`` ? Si je mets des mentions comme "bijoux" ou "lingot d’or", cela pourrait attirer des personnes mal intentionnées...


> 3\. et vu la galère que ça a été

C’est bien là le problème : chez les autres, on dirait que la même galère se profile aussi.

**Comment by frontBOI** [comment]
Oui il faut renseigner quelque chose dans le champ `Content`, mais rien ne vous obliger d'indiquer ce qu'il y a vraiment dedans... Ça ne regarde que vous !

> C’est bien là le problème : chez les autres, on dirait que la même galère se profile aussi.

Si besoin est, nous pourrons associer nos forces pour développer un autre package :-) car la majeure partie des connecteurs d'API sont développés pour les mastodontes, à savoir Shopify, Wordpress et compagnie... Place aux entrepreneurs et au Javascript !

**Comment by karimou5** [comment]
> Si besoin est, nous pourrons associer nos forces pour développer un autre package :-)

Je suis vraiment motivé par cela. Dès que j'aurai terminé le projet d'un client, je te contacterai en privé !

**Comment by frontBOI** [comment]
alors nous ferons cela @jins5 🤝🏼
